services:
  postgres:
    image: postgres:15-alpine
    container_name: pico_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5437:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: pico_redis
    restart: always
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_DECODE_RESPONSES: ${REDIS_DECODE_RESPONSES}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

  pico-minio:
    container_name: pico-minio
    image: minio/minio:latest
    environment:
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
    ports:
      - "9015:9000"
      - "9016:9001"
    volumes:
      - pico-minio-data:/var/lib/pico-minio
      - pico-minio-storage:/data
    restart: on-failure

volumes:
  postgres_data:
  redis_data:
  pico-minio-data:
  pico-minio-storage: