from enum import IntEnum


class CommonCodesEnum(IntEnum):
    DEFAULT = 0
    NOT_FOUND = 1
    ACCESS_DENIED = 2
    USERNAME_ALREADY_EXISTS = 3
    INCORRECT_PASSWORD = 4
    TOKEN_VALIDATION_ERROR = 5
    TOKEN_MISSING = 6
    USER_ALREADY_LOGOUT = 7
    UNKNOWN_ERROR = 8
    VALIDATION_ERROR = 9
    CHAT_ALREADY_EXISTS = 10
    RECEIVER_ID_EQ_USER_ID = 11
    EMAIL_ALREADY_IN_USE = 12
    INVALID_FILE_EXTENSION = 13
