"""add files

Revision ID: 5f432565f271
Revises: 65c4401e493b
Create Date: 2026-06-08 22:02:27.570264

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5f432565f271"
down_revision: str | Sequence[str] | None = "65c4401e493b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "files",
        sa.Column("sid", sa.UUID(), nullable=False),
        sa.Column("url", sa.String(length=200), nullable=True),
        sa.PrimaryKeyConstraint("sid"),
    )
    op.alter_column(
        "chats",
        "avatar",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=200),
        existing_nullable=True,
    )
    op.add_column(
        "messages", sa.Column("files_ids", sa.ARRAY(sa.UUID()), nullable=True)
    )
    op.alter_column(
        "users",
        "avatar",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=200),
        existing_nullable=True,
    )
    op.alter_column(
        "userschats",
        "avatar",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=200),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "userschats",
        "avatar",
        existing_type=sa.String(length=200),
        type_=sa.VARCHAR(length=100),
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "avatar",
        existing_type=sa.String(length=200),
        type_=sa.VARCHAR(length=100),
        existing_nullable=True,
    )
    op.drop_column("messages", "files_ids")
    op.alter_column(
        "chats",
        "avatar",
        existing_type=sa.String(length=200),
        type_=sa.VARCHAR(length=100),
        existing_nullable=True,
    )
    op.drop_table("files")
    # ### end Alembic commands ###
