"""inital

Revision ID: 65c4401e493b
Revises: 
Create Date: 2026-06-07 15:01:01.002627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65c4401e493b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('sid', sa.UUID(), nullable=False),
    sa.Column('avatar', sa.String(length=100), nullable=True),
    sa.Column('chat_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('sid')
    )
    op.create_table('users',
    sa.Column('sid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=36), nullable=False),
    sa.Column('surname', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=72), nullable=False),
    sa.Column('status', sa.String(length=72), nullable=True),
    sa.Column('avatar', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=144), nullable=False),
    sa.Column('password', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('sid'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('messages',
    sa.Column('sid', sa.UUID(), nullable=False),
    sa.Column('sender_sid', sa.UUID(), nullable=False),
    sa.Column('chat_sid', sa.UUID(), nullable=False),
    sa.Column('content', sa.String(length=4000), nullable=False),
    sa.Column('reply_message_sid', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['chat_sid'], ['chats.sid'], ),
    sa.ForeignKeyConstraint(['reply_message_sid'], ['messages.sid'], ),
    sa.ForeignKeyConstraint(['sender_sid'], ['users.sid'], ),
    sa.PrimaryKeyConstraint('sid')
    )
    op.create_table('userschats',
    sa.Column('user_sid', sa.UUID(), nullable=False),
    sa.Column('chat_sid', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('is_muted', sa.Boolean(), nullable=False),
    sa.Column('chat_name', sa.String(length=72), nullable=False),
    sa.Column('avatar', sa.String(length=100), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chat_sid'], ['chats.sid'], ),
    sa.ForeignKeyConstraint(['user_sid'], ['users.sid'], ),
    sa.PrimaryKeyConstraint('user_sid', 'chat_sid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userschats')
    op.drop_table('messages')
    op.drop_table('users')
    op.drop_table('chats')
    # ### end Alembic commands ###
