"""fix_chats_created_at_timezone

Revision ID: 6eeb7540c5e7
Revises: b6ebe661a30a
Create Date: 2026-04-28 23:31:44.125963

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Column
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6eeb7540c5e7"
down_revision: str | Sequence[str] | None = "b6ebe661a30a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "chats",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.add_column("messages", Column("is_deleted", type_=sa.Boolean(), default=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "chats",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    # ### end Alembic commands ###
