"""empty message

Revision ID: c36ecdf4a7dc
Revises:
Create Date: 2026-04-26 21:47:50.769291

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c36ecdf4a7dc"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chats",
        sa.Column("sid", sa.UUID(), nullable=False),
        sa.Column("chat_name", sa.String(length=72), nullable=False),
        sa.Column("avatar", sa.String(length=100), nullable=True),
        sa.Column("chat_type", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("sid"),
    )
    op.create_table(
        "users",
        sa.Column("sid", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=36), nullable=False),
        sa.Column("surname", sa.String(length=36), nullable=False),
        sa.Column("username", sa.String(length=72), nullable=False),
        sa.Column("status", sa.String(length=72), nullable=False),
        sa.Column("avatar", sa.String(length=100), nullable=True),
        sa.Column("email", sa.String(length=144), nullable=False),
        sa.Column("password", sa.String(length=500), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("sid"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "messages",
        sa.Column("sid", sa.UUID(), nullable=False),
        sa.Column("sender_sid", sa.UUID(), nullable=False),
        sa.Column("chat_sid", sa.UUID(), nullable=False),
        sa.Column("content", sa.String(length=4000), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reply_message_sid", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["chat_sid"],
            ["chats.sid"],
        ),
        sa.ForeignKeyConstraint(
            ["reply_message_sid"],
            ["messages.sid"],
        ),
        sa.ForeignKeyConstraint(
            ["sender_sid"],
            ["users.sid"],
        ),
        sa.PrimaryKeyConstraint("sid"),
    )
    op.create_table(
        "userschats",
        sa.Column("user_sid", sa.UUID(), nullable=False),
        sa.Column("chat_sid", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("is_pinned", sa.Boolean(), nullable=False),
        sa.Column("is_muted", sa.Boolean(), nullable=False),
        sa.Column(
            "joined_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("left_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["chat_sid"],
            ["chats.sid"],
        ),
        sa.ForeignKeyConstraint(
            ["user_sid"],
            ["users.sid"],
        ),
        sa.PrimaryKeyConstraint("user_sid", "chat_sid"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("userschats")
    op.drop_table("messages")
    op.drop_table("users")
    op.drop_table("chats")
    # ### end Alembic commands ###
