"""add birthday

Revision ID: c5e440a4ddd4
Revises: d05d8962b85b
Create Date: 2026-06-14 22:18:51.675263

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c5e440a4ddd4"
down_revision: str | Sequence[str] | None = "d05d8962b85b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("birthday", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "birthday")
    # ### end Alembic commands ###
