"""add wallpaper and files

Revision ID: d05d8962b85b
Revises: 65c4401e493b
Create Date: 2026-06-14 21:24:31.252390

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d05d8962b85b"
down_revision: str | Sequence[str] | None = "65c4401e493b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "files",
        sa.Column("sid", sa.UUID(), nullable=False),
        sa.Column("url", sa.String(length=200), nullable=True),
        sa.Column("extension", sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint("sid"),
    )
    op.add_column(
        "messages", sa.Column("files_ids", sa.ARRAY(sa.UUID()), nullable=True)
    )
    op.add_column(
        "userschats",
        sa.Column("wallpaper", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("userschats", "wallpaper")
    op.drop_column("messages", "files_ids")
    op.drop_table("files")
    # ### end Alembic commands ###
